
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.OrganizationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  logo: 'logo',
  address: 'address',
  legalName: 'legalName',
  tradingName: 'tradingName',
  regNumber: 'regNumber',
  taxNumber: 'taxNumber',
  contactEmail: 'contactEmail',
  contactPhone: 'contactPhone',
  country: 'country',
  timeZone: 'timeZone',
  status: 'status',
  healthScore: 'healthScore',
  lockedAt: 'lockedAt',
  lockedById: 'lockedById',
  suspendedAt: 'suspendedAt',
  suspensionReason: 'suspensionReason',
  activationOtp: 'activationOtp',
  activationOtpExpiresAt: 'activationOtpExpiresAt',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  emailVerified: 'emailVerified',
  image: 'image',
  phone: 'phone',
  mailingAddress: 'mailingAddress',
  emergencyContactName: 'emergencyContactName',
  emergencyContactPhone: 'emergencyContactPhone',
  status: 'status',
  lastLoginAt: 'lastLoginAt',
  mfaEnabled: 'mfaEnabled',
  passwordChangedAt: 'passwordChangedAt',
  preferredLanguage: 'preferredLanguage',
  preferredTimeZone: 'preferredTimeZone',
  marketingOptIn: 'marketingOptIn',
  organizationId: 'organizationId',
  departmentId: 'departmentId',
  vendorId: 'vendorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  organizationId: 'organizationId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PermissionScalarFieldEnum = {
  id: 'id',
  action: 'action',
  subject: 'subject',
  description: 'description'
};

exports.Prisma.RolePermissionScalarFieldEnum = {
  roleId: 'roleId',
  permissionId: 'permissionId'
};

exports.Prisma.UserRoleScalarFieldEnum = {
  userId: 'userId',
  roleId: 'roleId'
};

exports.Prisma.RoleTemplateScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  baseRole: 'baseRole',
  permissions: 'permissions',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  organizationId: 'organizationId',
  action: 'action',
  entity: 'entity',
  entityId: 'entityId',
  oldData: 'oldData',
  newData: 'newData',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  integrationId: 'integrationId',
  reason: 'reason',
  createdAt: 'createdAt'
};

exports.Prisma.PropertyScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  propertyCode: 'propertyCode',
  propertyName: 'propertyName',
  propertyType: 'propertyType',
  address: 'address',
  city: 'city',
  county: 'county',
  landlordId: 'landlordId',
  caretakerId: 'caretakerId',
  managerId: 'managerId',
  status: 'status',
  description: 'description',
  acquisitionDate: 'acquisitionDate',
  propertyValue: 'propertyValue',
  ownershipPercentage: 'ownershipPercentage',
  paybillNumber: 'paybillNumber',
  bankName: 'bankName',
  accountNumber: 'accountNumber',
  accountFormat: 'accountFormat',
  customFormat: 'customFormat',
  numberOfFloors: 'numberOfFloors',
  serviceChargeRate: 'serviceChargeRate',
  waterUnitRate: 'waterUnitRate',
  utilityDueRule: 'utilityDueRule',
  daysAfterReading: 'daysAfterReading',
  nextMonthDay: 'nextMonthDay',
  incomeTaxRate: 'incomeTaxRate',
  featuredImage: 'featuredImage',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.UnitScalarFieldEnum = {
  id: 'id',
  propertyId: 'propertyId',
  unitNumber: 'unitNumber',
  unitCode: 'unitCode',
  unitType: 'unitType',
  block: 'block',
  floor: 'floor',
  monthlyRent: 'monthlyRent',
  securityDeposit: 'securityDeposit',
  serviceCharge: 'serviceCharge',
  bedrooms: 'bedrooms',
  bathrooms: 'bathrooms',
  squareFootage: 'squareFootage',
  occupancyStatus: 'occupancyStatus',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.TenantScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  tenantCode: 'tenantCode',
  firstName: 'firstName',
  middleName: 'middleName',
  lastName: 'lastName',
  gender: 'gender',
  dateOfBirth: 'dateOfBirth',
  idNumber: 'idNumber',
  passportNumber: 'passportNumber',
  email: 'email',
  phone: 'phone',
  alternativePhone: 'alternativePhone',
  postalAddress: 'postalAddress',
  city: 'city',
  county: 'county',
  emergencyName: 'emergencyName',
  emergencyPhone: 'emergencyPhone',
  relationship: 'relationship',
  employer: 'employer',
  occupation: 'occupation',
  profilePhoto: 'profilePhoto',
  status: 'status',
  userId: 'userId',
  moveInDate: 'moveInDate',
  moveOutDate: 'moveOutDate',
  preferredContactMethod: 'preferredContactMethod',
  preferredContactHours: 'preferredContactHours',
  marketingOptIn: 'marketingOptIn',
  groupId: 'groupId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TenantGroupScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DocumentScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  tenantId: 'tenantId',
  name: 'name',
  description: 'description',
  url: 'url',
  category: 'category',
  status: 'status',
  fileType: 'fileType',
  fileSize: 'fileSize',
  version: 'version',
  expiryDate: 'expiryDate',
  uploadedById: 'uploadedById',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LeaseScalarFieldEnum = {
  id: 'id',
  leaseNumber: 'leaseNumber',
  organizationId: 'organizationId',
  propertyId: 'propertyId',
  unitId: 'unitId',
  tenantId: 'tenantId',
  monthlyRent: 'monthlyRent',
  securityDeposit: 'securityDeposit',
  serviceCharge: 'serviceCharge',
  lateFee: 'lateFee',
  billingDay: 'billingDay',
  startDate: 'startDate',
  endDate: 'endDate',
  moveInDate: 'moveInDate',
  moveOutDate: 'moveOutDate',
  paymentFrequency: 'paymentFrequency',
  leaseTermMonths: 'leaseTermMonths',
  noticePeriodDays: 'noticePeriodDays',
  status: 'status',
  signedLeaseUrl: 'signedLeaseUrl',
  terminationReason: 'terminationReason',
  previousLeaseId: 'previousLeaseId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  invoiceNumber: 'invoiceNumber',
  leaseId: 'leaseId',
  billingMonth: 'billingMonth',
  billingYear: 'billingYear',
  subtotal: 'subtotal',
  taxAmount: 'taxAmount',
  totalAmount: 'totalAmount',
  amountPaid: 'amountPaid',
  balanceDue: 'balanceDue',
  dueDate: 'dueDate',
  issuedDate: 'issuedDate',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvoiceLineItemScalarFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  description: 'description',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  amount: 'amount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  tenantId: 'tenantId',
  leaseId: 'leaseId',
  amount: 'amount',
  method: 'method',
  status: 'status',
  transactionRef: 'transactionRef',
  receiptNumber: 'receiptNumber',
  paymentDate: 'paymentDate',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  invoiceId: 'invoiceId'
};

exports.Prisma.PaymentAllocationScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  paymentId: 'paymentId',
  invoiceId: 'invoiceId',
  amount: 'amount',
  createdAt: 'createdAt'
};

exports.Prisma.CreditBalanceScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  tenantId: 'tenantId',
  amount: 'amount',
  updatedAt: 'updatedAt'
};

exports.Prisma.TenantLedgerScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  tenantId: 'tenantId',
  type: 'type',
  description: 'description',
  debit: 'debit',
  credit: 'credit',
  balance: 'balance',
  reference: 'reference',
  paymentId: 'paymentId',
  invoiceId: 'invoiceId',
  createdAt: 'createdAt'
};

exports.Prisma.ReceiptScalarFieldEnum = {
  id: 'id',
  paymentId: 'paymentId',
  receiptUrl: 'receiptUrl',
  createdAt: 'createdAt'
};

exports.Prisma.MpesaCredentialScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  consumerKey: 'consumerKey',
  consumerSecret: 'consumerSecret',
  shortCode: 'shortCode',
  passkey: 'passkey',
  environment: 'environment',
  callbackUrl: 'callbackUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MpesaTransactionScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  tenantId: 'tenantId',
  invoiceId: 'invoiceId',
  merchantRequestId: 'merchantRequestId',
  checkoutRequestId: 'checkoutRequestId',
  transactionType: 'transactionType',
  mpesaReceiptNumber: 'mpesaReceiptNumber',
  amount: 'amount',
  phoneNumber: 'phoneNumber',
  accountReference: 'accountReference',
  transactionDate: 'transactionDate',
  resultCode: 'resultCode',
  resultDesc: 'resultDesc',
  status: 'status',
  rawCallback: 'rawCallback',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MpesaCallbackLogScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  topic: 'topic',
  payload: 'payload',
  createdAt: 'createdAt'
};

exports.Prisma.ExpenseScalarFieldEnum = {
  id: 'id',
  expenseNumber: 'expenseNumber',
  organizationId: 'organizationId',
  propertyId: 'propertyId',
  unitId: 'unitId',
  vendorId: 'vendorId',
  categoryId: 'categoryId',
  expenseDate: 'expenseDate',
  dueDate: 'dueDate',
  amount: 'amount',
  taxAmount: 'taxAmount',
  totalAmount: 'totalAmount',
  paymentStatus: 'paymentStatus',
  paymentMethod: 'paymentMethod',
  status: 'status',
  notes: 'notes',
  rejectionReason: 'rejectionReason',
  createdById: 'createdById',
  approvedById: 'approvedById',
  approvalDate: 'approvalDate',
  isArchived: 'isArchived',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ExpenseCategoryScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  isSystem: 'isSystem',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VendorScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  contactPerson: 'contactPerson',
  phone: 'phone',
  email: 'email',
  taxPin: 'taxPin',
  address: 'address',
  notes: 'notes',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ExpenseAttachmentScalarFieldEnum = {
  id: 'id',
  expenseId: 'expenseId',
  url: 'url',
  name: 'name',
  type: 'type',
  size: 'size',
  createdAt: 'createdAt'
};

exports.Prisma.TicketScalarFieldEnum = {
  id: 'id',
  ticketNumber: 'ticketNumber',
  organizationId: 'organizationId',
  propertyId: 'propertyId',
  unitId: 'unitId',
  tenantId: 'tenantId',
  categoryId: 'categoryId',
  subject: 'subject',
  description: 'description',
  priority: 'priority',
  status: 'status',
  reportedBy: 'reportedBy',
  creatorId: 'creatorId',
  assigneeId: 'assigneeId',
  vendorId: 'vendorId',
  dueDate: 'dueDate',
  closedAt: 'closedAt',
  responseTimeTarget: 'responseTimeTarget',
  resolutionTarget: 'resolutionTarget',
  estimatedCost: 'estimatedCost',
  actualCost: 'actualCost',
  completionNotes: 'completionNotes',
  preferredAccessTime: 'preferredAccessTime',
  contactPreference: 'contactPreference',
  satisfactionRating: 'satisfactionRating',
  satisfactionFeedback: 'satisfactionFeedback',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expenseCategoryId: 'expenseCategoryId'
};

exports.Prisma.LeaseRenewalScalarFieldEnum = {
  id: 'id',
  leaseId: 'leaseId',
  organizationId: 'organizationId',
  status: 'status',
  proposedStartDate: 'proposedStartDate',
  proposedEndDate: 'proposedEndDate',
  proposedRent: 'proposedRent',
  deadline: 'deadline',
  tenantResponse: 'tenantResponse',
  tenantNotes: 'tenantNotes',
  respondedAt: 'respondedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LeaseNoticeScalarFieldEnum = {
  id: 'id',
  leaseId: 'leaseId',
  organizationId: 'organizationId',
  type: 'type',
  title: 'title',
  content: 'content',
  documentUrl: 'documentUrl',
  acknowledgedAt: 'acknowledgedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LeaseEventScalarFieldEnum = {
  id: 'id',
  leaseId: 'leaseId',
  type: 'type',
  description: 'description',
  eventDate: 'eventDate',
  metadata: 'metadata'
};

exports.Prisma.LeaseOccupantScalarFieldEnum = {
  id: 'id',
  leaseId: 'leaseId',
  name: 'name',
  relationship: 'relationship',
  idNumber: 'idNumber',
  phone: 'phone',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TicketActivityScalarFieldEnum = {
  id: 'id',
  ticketId: 'ticketId',
  userId: 'userId',
  type: 'type',
  content: 'content',
  oldValue: 'oldValue',
  newValue: 'newValue',
  isInternal: 'isInternal',
  createdAt: 'createdAt'
};

exports.Prisma.TicketCategoryScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  isSystem: 'isSystem',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TicketCommentScalarFieldEnum = {
  id: 'id',
  ticketId: 'ticketId',
  userId: 'userId',
  content: 'content',
  isInternal: 'isInternal',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TicketAssignmentScalarFieldEnum = {
  id: 'id',
  ticketId: 'ticketId',
  assigneeId: 'assigneeId',
  assignedById: 'assignedById',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.MaintenanceAttachmentScalarFieldEnum = {
  id: 'id',
  ticketId: 'ticketId',
  commentId: 'commentId',
  url: 'url',
  name: 'name',
  type: 'type',
  size: 'size',
  uploadedById: 'uploadedById',
  createdAt: 'createdAt'
};

exports.Prisma.CaseScalarFieldEnum = {
  id: 'id',
  caseNumber: 'caseNumber',
  organizationId: 'organizationId',
  propertyId: 'propertyId',
  unitId: 'unitId',
  tenantId: 'tenantId',
  categoryId: 'categoryId',
  subject: 'subject',
  description: 'description',
  severity: 'severity',
  status: 'status',
  creatorId: 'creatorId',
  assigneeId: 'assigneeId',
  openedAt: 'openedAt',
  closedAt: 'closedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CaseCategoryScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  isSystem: 'isSystem',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CaseActivityScalarFieldEnum = {
  id: 'id',
  caseId: 'caseId',
  userId: 'userId',
  type: 'type',
  content: 'content',
  oldValue: 'oldValue',
  newValue: 'newValue',
  createdAt: 'createdAt'
};

exports.Prisma.CaseEvidenceScalarFieldEnum = {
  id: 'id',
  caseId: 'caseId',
  url: 'url',
  name: 'name',
  type: 'type',
  size: 'size',
  uploadedById: 'uploadedById',
  createdAt: 'createdAt'
};

exports.Prisma.CaseDecisionScalarFieldEnum = {
  id: 'id',
  caseId: 'caseId',
  decidedById: 'decidedById',
  summary: 'summary',
  resolutionNotes: 'resolutionNotes',
  financialImpact: 'financialImpact',
  followUpActions: 'followUpActions',
  closureReason: 'closureReason',
  createdAt: 'createdAt'
};

exports.Prisma.SecurityIncidentScalarFieldEnum = {
  id: 'id',
  logNumber: 'logNumber',
  organizationId: 'organizationId',
  propertyId: 'propertyId',
  categoryId: 'categoryId',
  subject: 'subject',
  description: 'description',
  severity: 'severity',
  status: 'status',
  reportedBy: 'reportedBy',
  recordedById: 'recordedById',
  followUpRequired: 'followUpRequired',
  resolvedAt: 'resolvedAt',
  closedAt: 'closedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SecurityIncidentCategoryScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  isSystem: 'isSystem',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SecurityVisitorScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  visitorName: 'visitorName',
  idNumber: 'idNumber',
  phoneNumber: 'phoneNumber',
  vehicleReg: 'vehicleReg',
  purpose: 'purpose',
  hostTenantId: 'hostTenantId',
  unitVisited: 'unitVisited',
  checkInTime: 'checkInTime',
  checkOutTime: 'checkOutTime',
  securityOfficerId: 'securityOfficerId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SecurityPatrolScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  officerId: 'officerId',
  startTime: 'startTime',
  endTime: 'endTime',
  checkpoints: 'checkpoints',
  findings: 'findings',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.SecurityShiftHandoverScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  incomingOfficerId: 'incomingOfficerId',
  outgoingOfficerId: 'outgoingOfficerId',
  shiftNotes: 'shiftNotes',
  outstandingIssues: 'outstandingIssues',
  equipmentHandover: 'equipmentHandover',
  handoverTime: 'handoverTime',
  createdAt: 'createdAt'
};

exports.Prisma.SecurityActivityScalarFieldEnum = {
  id: 'id',
  incidentId: 'incidentId',
  userId: 'userId',
  type: 'type',
  content: 'content',
  oldValue: 'oldValue',
  newValue: 'newValue',
  createdAt: 'createdAt'
};

exports.Prisma.SecurityEvidenceScalarFieldEnum = {
  id: 'id',
  incidentId: 'incidentId',
  url: 'url',
  name: 'name',
  type: 'type',
  size: 'size',
  uploadedById: 'uploadedById',
  createdAt: 'createdAt'
};

exports.Prisma.CommunicationScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  type: 'type',
  status: 'status',
  recipient: 'recipient',
  subject: 'subject',
  content: 'content',
  metadata: 'metadata',
  sentAt: 'sentAt',
  deliveredAt: 'deliveredAt',
  errorMessage: 'errorMessage',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CommunicationTemplateScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  type: 'type',
  subject: 'subject',
  body: 'body',
  variables: 'variables',
  isSystem: 'isSystem',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AnnouncementScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  title: 'title',
  content: 'content',
  category: 'category',
  priority: 'priority',
  targetType: 'targetType',
  targetIds: 'targetIds',
  status: 'status',
  scheduledAt: 'scheduledAt',
  sentAt: 'sentAt',
  expiresAt: 'expiresAt',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AnnouncementAttachmentScalarFieldEnum = {
  id: 'id',
  announcementId: 'announcementId',
  name: 'name',
  url: 'url',
  type: 'type',
  size: 'size',
  createdAt: 'createdAt'
};

exports.Prisma.AnnouncementReadScalarFieldEnum = {
  id: 'id',
  announcementId: 'announcementId',
  userId: 'userId',
  readAt: 'readAt',
  acknowledgedAt: 'acknowledgedAt',
  method: 'method'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  userId: 'userId',
  title: 'title',
  message: 'message',
  type: 'type',
  priority: 'priority',
  link: 'link',
  metadata: 'metadata',
  readAt: 'readAt',
  archivedAt: 'archivedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlanScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  price: 'price',
  interval: 'interval',
  features: 'features',
  isActive: 'isActive',
  isRetired: 'isRetired',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SubscriptionScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  planId: 'planId',
  status: 'status',
  startDate: 'startDate',
  endDate: 'endDate',
  trialEndsAt: 'trialEndsAt',
  billingCycleAnchor: 'billingCycleAnchor',
  cancelAtPeriodEnd: 'cancelAtPeriodEnd',
  canceledAt: 'canceledAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BillingInvoiceScalarFieldEnum = {
  id: 'id',
  invoiceNumber: 'invoiceNumber',
  organizationId: 'organizationId',
  subscriptionId: 'subscriptionId',
  periodStart: 'periodStart',
  periodEnd: 'periodEnd',
  amount: 'amount',
  tax: 'tax',
  total: 'total',
  status: 'status',
  dunningStatus: 'dunningStatus',
  retryCount: 'retryCount',
  nextRetryDate: 'nextRetryDate',
  dueDate: 'dueDate',
  paidAt: 'paidAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BillingInvoiceItemScalarFieldEnum = {
  id: 'id',
  billingInvoiceId: 'billingInvoiceId',
  description: 'description',
  amount: 'amount',
  createdAt: 'createdAt'
};

exports.Prisma.BillingPaymentScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  billingInvoiceId: 'billingInvoiceId',
  amount: 'amount',
  method: 'method',
  status: 'status',
  transactionRef: 'transactionRef',
  paymentDate: 'paymentDate',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.UsageMetricScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  metricType: 'metricType',
  value: 'value',
  recordedAt: 'recordedAt'
};

exports.Prisma.PlatformMetricRollupScalarFieldEnum = {
  id: 'id',
  metricType: 'metricType',
  value: 'value',
  period: 'period',
  timestamp: 'timestamp',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.AnalyticsReportScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  type: 'type',
  config: 'config',
  isScheduled: 'isScheduled',
  scheduleCron: 'scheduleCron',
  lastRunAt: 'lastRunAt',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RetentionPolicyScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  entityType: 'entityType',
  periodYears: 'periodYears',
  updatedAt: 'updatedAt'
};

exports.Prisma.ComplianceRecordScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  propertyId: 'propertyId',
  type: 'type',
  title: 'title',
  description: 'description',
  documentUrl: 'documentUrl',
  effectiveDate: 'effectiveDate',
  expiryDate: 'expiryDate',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RecordAccessLogScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  userId: 'userId',
  action: 'action',
  entityType: 'entityType',
  entityId: 'entityId',
  details: 'details',
  createdAt: 'createdAt'
};

exports.Prisma.UtilityTypeScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  unitOfMeasure: 'unitOfMeasure',
  isSystem: 'isSystem',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UtilityMeterScalarFieldEnum = {
  id: 'id',
  meterNumber: 'meterNumber',
  organizationId: 'organizationId',
  propertyId: 'propertyId',
  unitId: 'unitId',
  utilityTypeId: 'utilityTypeId',
  status: 'status',
  installationDate: 'installationDate',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UtilityReadingScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  meterId: 'meterId',
  previousReading: 'previousReading',
  currentReading: 'currentReading',
  consumption: 'consumption',
  readingDate: 'readingDate',
  readingImage: 'readingImage',
  status: 'status',
  recordedById: 'recordedById',
  approvedById: 'approvedById',
  approvedAt: 'approvedAt',
  notes: 'notes',
  invoiceLineItemId: 'invoiceLineItemId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UtilityBillingRuleScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  propertyId: 'propertyId',
  utilityTypeId: 'utilityTypeId',
  basis: 'basis',
  fixedAmount: 'fixedAmount',
  unitPrice: 'unitPrice',
  tiers: 'tiers',
  minimumCharge: 'minimumCharge',
  taxPercentage: 'taxPercentage',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SuperAdminApiTokenScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  token: 'token',
  scopes: 'scopes',
  expiresAt: 'expiresAt',
  lastUsedAt: 'lastUsedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DepartmentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  organizationId: 'organizationId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LoginHistoryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.AccessReviewScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  reviewerId: 'reviewerId',
  reviewDate: 'reviewDate',
  findings: 'findings',
  actionsTaken: 'actionsTaken',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.ApprovalWorkflowScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  entityType: 'entityType',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ApprovalStepScalarFieldEnum = {
  id: 'id',
  workflowId: 'workflowId',
  order: 'order',
  roleId: 'roleId'
};

exports.Prisma.ApprovalDecisionScalarFieldEnum = {
  id: 'id',
  stepId: 'stepId',
  entityId: 'entityId',
  approverId: 'approverId',
  decision: 'decision',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.SupportCategoryScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  slug: 'slug',
  description: 'description',
  isSystem: 'isSystem',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SupportTagScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  createdAt: 'createdAt'
};

exports.Prisma.SupportArticleScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  title: 'title',
  slug: 'slug',
  content: 'content',
  status: 'status',
  categoryId: 'categoryId',
  authorId: 'authorId',
  currentVersion: 'currentVersion',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SupportArticleVersionScalarFieldEnum = {
  id: 'id',
  articleId: 'articleId',
  version: 'version',
  title: 'title',
  content: 'content',
  changeSummary: 'changeSummary',
  authorId: 'authorId',
  createdAt: 'createdAt'
};

exports.Prisma.SupportDocumentScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  title: 'title',
  description: 'description',
  fileUrl: 'fileUrl',
  fileType: 'fileType',
  category: 'category',
  uploadedById: 'uploadedById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DownloadLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  supportDocumentId: 'supportDocumentId',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  createdAt: 'createdAt'
};

exports.Prisma.PropertyDocumentScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  propertyId: 'propertyId',
  name: 'name',
  description: 'description',
  url: 'url',
  category: 'category',
  status: 'status',
  fileType: 'fileType',
  fileSize: 'fileSize',
  version: 'version',
  publishedAt: 'publishedAt',
  uploadedById: 'uploadedById',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotificationPreferenceScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  inApp: 'inApp',
  email: 'email',
  sms: 'sms',
  invoiceAlerts: 'invoiceAlerts',
  paymentConfirmations: 'paymentConfirmations',
  leaseReminders: 'leaseReminders',
  maintenanceUpdates: 'maintenanceUpdates',
  announcementAlerts: 'announcementAlerts',
  securityNotices: 'securityNotices',
  financialReports: 'financialReports',
  statementAvailability: 'statementAvailability',
  complianceNotices: 'complianceNotices',
  communications: 'communications',
  updatedAt: 'updatedAt'
};

exports.Prisma.ConsentRecordScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  version: 'version',
  acceptedAt: 'acceptedAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  lastActiveAt: 'lastActiveAt'
};

exports.Prisma.OwnerStatementScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  landlordId: 'landlordId',
  statementNumber: 'statementNumber',
  startDate: 'startDate',
  endDate: 'endDate',
  generatedAt: 'generatedAt',
  revenue: 'revenue',
  expenses: 'expenses',
  netIncome: 'netIncome',
  disbursements: 'disbursements',
  openingBalance: 'openingBalance',
  closingBalance: 'closingBalance',
  status: 'status',
  documentUrl: 'documentUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OwnerStatementLineScalarFieldEnum = {
  id: 'id',
  ownerStatementId: 'ownerStatementId',
  date: 'date',
  description: 'description',
  type: 'type',
  amount: 'amount',
  reference: 'reference',
  createdAt: 'createdAt'
};

exports.Prisma.DisbursementScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  landlordId: 'landlordId',
  disbursementNumber: 'disbursementNumber',
  amount: 'amount',
  method: 'method',
  status: 'status',
  reference: 'reference',
  processedAt: 'processedAt',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LandlordFavoriteDocumentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  documentId: 'documentId',
  createdAt: 'createdAt'
};

exports.Prisma.ConversationScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  subject: 'subject',
  category: 'category',
  priority: 'priority',
  lastMessageAt: 'lastMessageAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ConversationParticipantScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  userId: 'userId',
  lastReadAt: 'lastReadAt'
};

exports.Prisma.MessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  senderId: 'senderId',
  content: 'content',
  isInternal: 'isInternal',
  createdAt: 'createdAt'
};

exports.Prisma.MessageAttachmentScalarFieldEnum = {
  id: 'id',
  messageId: 'messageId',
  name: 'name',
  url: 'url',
  type: 'type',
  size: 'size',
  createdAt: 'createdAt'
};

exports.Prisma.SupportCaseScalarFieldEnum = {
  id: 'id',
  caseNumber: 'caseNumber',
  organizationId: 'organizationId',
  requesterId: 'requesterId',
  subject: 'subject',
  description: 'description',
  priority: 'priority',
  status: 'status',
  category: 'category',
  agentId: 'agentId',
  slaDeadline: 'slaDeadline',
  resolvedAt: 'resolvedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaskScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  title: 'title',
  description: 'description',
  priority: 'priority',
  status: 'status',
  type: 'type',
  projectId: 'projectId',
  propertyId: 'propertyId',
  unitId: 'unitId',
  tenantId: 'tenantId',
  landlordId: 'landlordId',
  assigneeId: 'assigneeId',
  creatorId: 'creatorId',
  dueDate: 'dueDate',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProjectScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SubtaskScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  title: 'title',
  isCompleted: 'isCompleted',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaskCommentScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  userId: 'userId',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaskAttachmentScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  url: 'url',
  name: 'name',
  type: 'type',
  size: 'size',
  createdAt: 'createdAt'
};

exports.Prisma.ImpersonationSessionScalarFieldEnum = {
  id: 'id',
  impersonatorId: 'impersonatorId',
  targetUserId: 'targetUserId',
  organizationId: 'organizationId',
  reason: 'reason',
  caseReference: 'caseReference',
  startTime: 'startTime',
  endTime: 'endTime',
  expiresAt: 'expiresAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.PlatformSecurityIncidentScalarFieldEnum = {
  id: 'id',
  incidentNumber: 'incidentNumber',
  title: 'title',
  description: 'description',
  status: 'status',
  severity: 'severity',
  investigatorId: 'investigatorId',
  organizationId: 'organizationId',
  targetUserId: 'targetUserId',
  metadata: 'metadata',
  resolvedAt: 'resolvedAt',
  closedAt: 'closedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlatformSecurityAlertScalarFieldEnum = {
  id: 'id',
  type: 'type',
  description: 'description',
  severity: 'severity',
  status: 'status',
  organizationId: 'organizationId',
  userId: 'userId',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.PlatformIntegrationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  provider: 'provider',
  description: 'description',
  isEnabled: 'isEnabled',
  config: 'config',
  isGlobal: 'isGlobal',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlatformJobScalarFieldEnum = {
  id: 'id',
  jobType: 'jobType',
  status: 'status',
  priority: 'priority',
  organizationId: 'organizationId',
  integrationId: 'integrationId',
  payload: 'payload',
  result: 'result',
  error: 'error',
  stackTrace: 'stackTrace',
  attempts: 'attempts',
  maxAttempts: 'maxAttempts',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  nextRunAt: 'nextRunAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlatformWebhookScalarFieldEnum = {
  id: 'id',
  integrationId: 'integrationId',
  endpoint: 'endpoint',
  description: 'description',
  secret: 'secret',
  isEnabled: 'isEnabled',
  lastDeliveryAt: 'lastDeliveryAt',
  successRate: 'successRate',
  failureRate: 'failureRate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlatformWebhookDeliveryScalarFieldEnum = {
  id: 'id',
  webhookId: 'webhookId',
  payload: 'payload',
  response: 'response',
  statusCode: 'statusCode',
  duration: 'duration',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.PlatformScheduledTaskScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  cronExpression: 'cronExpression',
  taskType: 'taskType',
  lastRunAt: 'lastRunAt',
  nextRunAt: 'nextRunAt',
  isEnabled: 'isEnabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FeatureFlagScalarFieldEnum = {
  id: 'id',
  name: 'name',
  key: 'key',
  description: 'description',
  status: 'status',
  scope: 'scope',
  rolloutPercentage: 'rolloutPercentage',
  config: 'config',
  activeAt: 'activeAt',
  expiresAt: 'expiresAt',
  lastModifiedById: 'lastModifiedById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FeatureFlagOverrideScalarFieldEnum = {
  id: 'id',
  flagId: 'flagId',
  organizationId: 'organizationId',
  isEnabled: 'isEnabled',
  reason: 'reason',
  configOverride: 'configOverride',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FeatureFlagVersionScalarFieldEnum = {
  id: 'id',
  flagId: 'flagId',
  versionData: 'versionData',
  reason: 'reason',
  createdById: 'createdById',
  createdAt: 'createdAt'
};

exports.Prisma.PlatformConfigurationScalarFieldEnum = {
  id: 'id',
  category: 'category',
  key: 'key',
  value: 'value',
  description: 'description',
  isSensitive: 'isSensitive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlatformIncidentScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  severity: 'severity',
  status: 'status',
  commanderId: 'commanderId',
  startedAt: 'startedAt',
  resolvedAt: 'resolvedAt',
  postmortem: 'postmortem',
  isPublic: 'isPublic',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlatformIncidentUpdateScalarFieldEnum = {
  id: 'id',
  incidentId: 'incidentId',
  status: 'status',
  content: 'content',
  createdById: 'createdById',
  createdAt: 'createdAt'
};

exports.Prisma.PlatformAffectedSystemScalarFieldEnum = {
  id: 'id',
  incidentId: 'incidentId',
  systemName: 'systemName',
  status: 'status'
};

exports.Prisma.PlatformStatusEntryScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  type: 'type',
  status: 'status',
  scheduledStart: 'scheduledStart',
  scheduledEnd: 'scheduledEnd',
  isPublic: 'isPublic',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlatformAlertRuleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  metricType: 'metricType',
  condition: 'condition',
  threshold: 'threshold',
  periodMinutes: 'periodMinutes',
  channels: 'channels',
  isEnabled: 'isEnabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReportTemplateScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  category: 'category',
  reportType: 'reportType',
  config: 'config',
  isSystem: 'isSystem',
  isPublic: 'isPublic',
  isFavourite: 'isFavourite',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SavedReportScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  templateId: 'templateId',
  name: 'name',
  filters: 'filters',
  data: 'data',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ScheduledReportScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  templateId: 'templateId',
  frequency: 'frequency',
  cron: 'cron',
  recipients: 'recipients',
  lastRunAt: 'lastRunAt',
  nextRunAt: 'nextRunAt',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReportExecutionScalarFieldEnum = {
  id: 'id',
  scheduledReportId: 'scheduledReportId',
  status: 'status',
  errorMessage: 'errorMessage',
  duration: 'duration',
  outputUrl: 'outputUrl',
  createdAt: 'createdAt'
};

exports.Prisma.ReportExportScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  reportType: 'reportType',
  format: 'format',
  status: 'status',
  filters: 'filters',
  downloadUrl: 'downloadUrl',
  expiresAt: 'expiresAt',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CollectionSettingScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  gracePeriod: 'gracePeriod',
  upcomingDueDays: 'upcomingDueDays',
  overdueDays: 'overdueDays',
  autoEscalateAfter: 'autoEscalateAfter',
  enableBalanceSms: 'enableBalanceSms',
  firstSendDay: 'firstSendDay',
  repeatEvery: 'repeatEvery',
  smsTemplate: 'smsTemplate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.OrganizationStatus = exports.$Enums.OrganizationStatus = {
  TRIAL: 'TRIAL',
  ACTIVE: 'ACTIVE',
  PAYMENT_DUE: 'PAYMENT_DUE',
  GRACE_PERIOD: 'GRACE_PERIOD',
  SUSPENSION_PENDING: 'SUSPENSION_PENDING',
  SUSPENDED: 'SUSPENDED',
  CANCELLED: 'CANCELLED',
  ARCHIVED: 'ARCHIVED'
};

exports.UserStatus = exports.$Enums.UserStatus = {
  INVITED: 'INVITED',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DEACTIVATED: 'DEACTIVATED',
  LOCKED: 'LOCKED',
  ARCHIVED: 'ARCHIVED'
};

exports.OccupancyStatus = exports.$Enums.OccupancyStatus = {
  VACANT: 'VACANT',
  OCCUPIED: 'OCCUPIED',
  RESERVED: 'RESERVED',
  MAINTENANCE: 'MAINTENANCE'
};

exports.UnitStatus = exports.$Enums.UnitStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

exports.TenantStatus = exports.$Enums.TenantStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  BLACKLISTED: 'BLACKLISTED',
  FORMER: 'FORMER'
};

exports.DocumentCategory = exports.$Enums.DocumentCategory = {
  LEASE_AGREEMENT: 'LEASE_AGREEMENT',
  RECEIPT: 'RECEIPT',
  NOTICE: 'NOTICE',
  INSPECTION_REPORT: 'INSPECTION_REPORT',
  MOVE_IN_DOCUMENT: 'MOVE_IN_DOCUMENT',
  MOVE_OUT_DOCUMENT: 'MOVE_OUT_DOCUMENT',
  COMPLIANCE_DOCUMENT: 'COMPLIANCE_DOCUMENT',
  UTILITY_STATEMENT: 'UTILITY_STATEMENT',
  OTHER: 'OTHER'
};

exports.DocumentStatus = exports.$Enums.DocumentStatus = {
  AVAILABLE: 'AVAILABLE',
  ARCHIVED: 'ARCHIVED',
  EXPIRED: 'EXPIRED'
};

exports.LeaseStatus = exports.$Enums.LeaseStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  EXPIRING: 'EXPIRING',
  EXPIRED: 'EXPIRED',
  TERMINATED: 'TERMINATED',
  RENEWED: 'RENEWED'
};

exports.InvoiceStatus = exports.$Enums.InvoiceStatus = {
  DRAFT: 'DRAFT',
  POSTED: 'POSTED',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  CASH: 'CASH',
  MPESA: 'MPESA',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CHEQUE: 'CHEQUE',
  OTHER: 'OTHER'
};

exports.PaymentStatus = exports.$Enums.PaymentStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  REVERSED: 'REVERSED',
  FAILED: 'FAILED'
};

exports.LedgerEntryType = exports.$Enums.LedgerEntryType = {
  INVOICE: 'INVOICE',
  PAYMENT: 'PAYMENT',
  CREDIT: 'CREDIT',
  ADJUSTMENT: 'ADJUSTMENT',
  REVERSAL: 'REVERSAL'
};

exports.ExpenseStatus = exports.$Enums.ExpenseStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PAID: 'PAID',
  VOIDED: 'VOIDED'
};

exports.TicketPriority = exports.$Enums.TicketPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
  EMERGENCY: 'EMERGENCY'
};

exports.TicketStatus = exports.$Enums.TicketStatus = {
  OPEN: 'OPEN',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  AWAITING_TENANT: 'AWAITING_TENANT',
  AWAITING_VENDOR: 'AWAITING_VENDOR',
  ESCALATED: 'ESCALATED',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REOPENED: 'REOPENED',
  ARCHIVED: 'ARCHIVED'
};

exports.TicketActivityType = exports.$Enums.TicketActivityType = {
  COMMENT: 'COMMENT',
  STATUS_CHANGE: 'STATUS_CHANGE',
  ASSIGNMENT: 'ASSIGNMENT',
  ESCALATION: 'ESCALATION',
  ATTACHMENT_ADDED: 'ATTACHMENT_ADDED',
  REOPENED: 'REOPENED',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED',
  SLA_BREACH: 'SLA_BREACH'
};

exports.CaseSeverity = exports.$Enums.CaseSeverity = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

exports.CaseStatus = exports.$Enums.CaseStatus = {
  OPEN: 'OPEN',
  UNDER_REVIEW: 'UNDER_REVIEW',
  INVESTIGATING: 'INVESTIGATING',
  AWAITING_INFORMATION: 'AWAITING_INFORMATION',
  ESCALATED: 'ESCALATED',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REOPENED: 'REOPENED',
  ARCHIVED: 'ARCHIVED'
};

exports.CaseActivityType = exports.$Enums.CaseActivityType = {
  COMMENT: 'COMMENT',
  STATUS_CHANGE: 'STATUS_CHANGE',
  ASSIGNMENT: 'ASSIGNMENT',
  ESCALATION: 'ESCALATION',
  EVIDENCE_ADDED: 'EVIDENCE_ADDED',
  DECISION: 'DECISION',
  REOPENED: 'REOPENED',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED'
};

exports.SecurityIncidentSeverity = exports.$Enums.SecurityIncidentSeverity = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

exports.SecurityIncidentStatus = exports.$Enums.SecurityIncidentStatus = {
  OPEN: 'OPEN',
  UNDER_INVESTIGATION: 'UNDER_INVESTIGATION',
  MONITORING: 'MONITORING',
  ESCALATED: 'ESCALATED',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED'
};

exports.SecurityActivityType = exports.$Enums.SecurityActivityType = {
  INCIDENT_CREATED: 'INCIDENT_CREATED',
  STATUS_CHANGE: 'STATUS_CHANGE',
  COMMENT: 'COMMENT',
  EVIDENCE_ADDED: 'EVIDENCE_ADDED',
  VISITOR_CHECKIN: 'VISITOR_CHECKIN',
  VISITOR_CHECKOUT: 'VISITOR_CHECKOUT',
  PATROL_START: 'PATROL_START',
  PATROL_END: 'PATROL_END',
  SHIFT_HANDOVER: 'SHIFT_HANDOVER',
  ESCALATION: 'ESCALATION'
};

exports.CommunicationType = exports.$Enums.CommunicationType = {
  SMS: 'SMS',
  EMAIL: 'EMAIL',
  WHATSAPP: 'WHATSAPP',
  IN_APP: 'IN_APP'
};

exports.CommunicationStatus = exports.$Enums.CommunicationStatus = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  READ: 'READ'
};

exports.AnnouncementCategory = exports.$Enums.AnnouncementCategory = {
  GENERAL: 'GENERAL',
  MAINTENANCE: 'MAINTENANCE',
  UTILITIES: 'UTILITIES',
  SECURITY: 'SECURITY',
  BILLING: 'BILLING',
  COMMUNITY: 'COMMUNITY',
  EMERGENCY: 'EMERGENCY'
};

exports.AnnouncementPriority = exports.$Enums.AnnouncementPriority = {
  NORMAL: 'NORMAL',
  IMPORTANT: 'IMPORTANT',
  URGENT: 'URGENT'
};

exports.NotificationPriority = exports.$Enums.NotificationPriority = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

exports.BillingInterval = exports.$Enums.BillingInterval = {
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY'
};

exports.SubscriptionStatus = exports.$Enums.SubscriptionStatus = {
  TRIAL: 'TRIAL',
  ACTIVE: 'ACTIVE',
  PAST_DUE: 'PAST_DUE',
  CANCELED: 'CANCELED',
  EXPIRED: 'EXPIRED'
};

exports.MeterStatus = exports.$Enums.MeterStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  FAULTY: 'FAULTY',
  REPLACED: 'REPLACED'
};

exports.ReadingStatus = exports.$Enums.ReadingStatus = {
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  VOIDED: 'VOIDED',
  BILLED: 'BILLED'
};

exports.BillingBasis = exports.$Enums.BillingBasis = {
  FIXED: 'FIXED',
  CONSUMPTION: 'CONSUMPTION',
  TIERED: 'TIERED',
  SHARED_PERCENTAGE: 'SHARED_PERCENTAGE',
  SHARED_EQUAL: 'SHARED_EQUAL'
};

exports.SupportArticleStatus = exports.$Enums.SupportArticleStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED'
};

exports.SupportCasePriority = exports.$Enums.SupportCasePriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

exports.SupportCaseStatus = exports.$Enums.SupportCaseStatus = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  AWAITING_CUSTOMER: 'AWAITING_CUSTOMER',
  ESCALATED: 'ESCALATED',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
};

exports.TaskPriority = exports.$Enums.TaskPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

exports.TaskStatus = exports.$Enums.TaskStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING: 'WAITING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  OVERDUE: 'OVERDUE'
};

exports.PlatformSecurityIncidentStatus = exports.$Enums.PlatformSecurityIncidentStatus = {
  OPEN: 'OPEN',
  INVESTIGATING: 'INVESTIGATING',
  ESCALATED: 'ESCALATED',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
};

exports.PlatformSecurityIncidentSeverity = exports.$Enums.PlatformSecurityIncidentSeverity = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

exports.IntegrationType = exports.$Enums.IntegrationType = {
  FINANCIAL: 'FINANCIAL',
  COMMUNICATION: 'COMMUNICATION',
  STORAGE: 'STORAGE',
  AUTHENTICATION: 'AUTHENTICATION'
};

exports.IntegrationProvider = exports.$Enums.IntegrationProvider = {
  MPESA: 'MPESA',
  STRIPE: 'STRIPE',
  PAYPAL: 'PAYPAL',
  TWILIO: 'TWILIO',
  SENDGRID: 'SENDGRID',
  AWS_S3: 'AWS_S3',
  CLOUDINARY: 'CLOUDINARY',
  GOOGLE_SSO: 'GOOGLE_SSO',
  MICROSOFT_SSO: 'MICROSOFT_SSO'
};

exports.JobStatus = exports.$Enums.JobStatus = {
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  RETRYING: 'RETRYING',
  CANCELLED: 'CANCELLED'
};

exports.FeatureStatus = exports.$Enums.FeatureStatus = {
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED',
  SCHEDULED: 'SCHEDULED',
  BETA: 'BETA',
  EXPERIMENT: 'EXPERIMENT'
};

exports.FeatureScope = exports.$Enums.FeatureScope = {
  GLOBAL: 'GLOBAL',
  ORGANIZATION: 'ORGANIZATION',
  PLAN: 'PLAN',
  USER_SEGMENT: 'USER_SEGMENT'
};

exports.ConfigCategory = exports.$Enums.ConfigCategory = {
  PLATFORM: 'PLATFORM',
  BUSINESS: 'BUSINESS',
  SECURITY: 'SECURITY',
  FINANCIAL: 'FINANCIAL',
  COMMUNICATION: 'COMMUNICATION'
};

exports.IncidentSeverity = exports.$Enums.IncidentSeverity = {
  SEV1: 'SEV1',
  SEV2: 'SEV2',
  SEV3: 'SEV3',
  SEV4: 'SEV4'
};

exports.IncidentStatus = exports.$Enums.IncidentStatus = {
  INVESTIGATING: 'INVESTIGATING',
  IDENTIFIED: 'IDENTIFIED',
  MONITORING: 'MONITORING',
  RESOLVED: 'RESOLVED'
};

exports.ReportCategory = exports.$Enums.ReportCategory = {
  FINANCIAL: 'FINANCIAL',
  OPERATIONAL: 'OPERATIONAL',
  PLATFORM: 'PLATFORM',
  CUSTOM: 'CUSTOM'
};

exports.Prisma.ModelName = {
  Organization: 'Organization',
  User: 'User',
  Role: 'Role',
  Permission: 'Permission',
  RolePermission: 'RolePermission',
  UserRole: 'UserRole',
  RoleTemplate: 'RoleTemplate',
  AuditLog: 'AuditLog',
  Property: 'Property',
  Unit: 'Unit',
  Tenant: 'Tenant',
  TenantGroup: 'TenantGroup',
  Document: 'Document',
  Lease: 'Lease',
  Invoice: 'Invoice',
  InvoiceLineItem: 'InvoiceLineItem',
  Payment: 'Payment',
  PaymentAllocation: 'PaymentAllocation',
  CreditBalance: 'CreditBalance',
  TenantLedger: 'TenantLedger',
  Receipt: 'Receipt',
  MpesaCredential: 'MpesaCredential',
  MpesaTransaction: 'MpesaTransaction',
  MpesaCallbackLog: 'MpesaCallbackLog',
  Expense: 'Expense',
  ExpenseCategory: 'ExpenseCategory',
  Vendor: 'Vendor',
  ExpenseAttachment: 'ExpenseAttachment',
  Ticket: 'Ticket',
  LeaseRenewal: 'LeaseRenewal',
  LeaseNotice: 'LeaseNotice',
  LeaseEvent: 'LeaseEvent',
  LeaseOccupant: 'LeaseOccupant',
  TicketActivity: 'TicketActivity',
  TicketCategory: 'TicketCategory',
  TicketComment: 'TicketComment',
  TicketAssignment: 'TicketAssignment',
  MaintenanceAttachment: 'MaintenanceAttachment',
  Case: 'Case',
  CaseCategory: 'CaseCategory',
  CaseActivity: 'CaseActivity',
  CaseEvidence: 'CaseEvidence',
  CaseDecision: 'CaseDecision',
  SecurityIncident: 'SecurityIncident',
  SecurityIncidentCategory: 'SecurityIncidentCategory',
  SecurityVisitor: 'SecurityVisitor',
  SecurityPatrol: 'SecurityPatrol',
  SecurityShiftHandover: 'SecurityShiftHandover',
  SecurityActivity: 'SecurityActivity',
  SecurityEvidence: 'SecurityEvidence',
  Communication: 'Communication',
  CommunicationTemplate: 'CommunicationTemplate',
  Announcement: 'Announcement',
  AnnouncementAttachment: 'AnnouncementAttachment',
  AnnouncementRead: 'AnnouncementRead',
  Notification: 'Notification',
  Plan: 'Plan',
  Subscription: 'Subscription',
  BillingInvoice: 'BillingInvoice',
  BillingInvoiceItem: 'BillingInvoiceItem',
  BillingPayment: 'BillingPayment',
  UsageMetric: 'UsageMetric',
  PlatformMetricRollup: 'PlatformMetricRollup',
  AnalyticsReport: 'AnalyticsReport',
  RetentionPolicy: 'RetentionPolicy',
  ComplianceRecord: 'ComplianceRecord',
  RecordAccessLog: 'RecordAccessLog',
  UtilityType: 'UtilityType',
  UtilityMeter: 'UtilityMeter',
  UtilityReading: 'UtilityReading',
  UtilityBillingRule: 'UtilityBillingRule',
  SuperAdminApiToken: 'SuperAdminApiToken',
  Department: 'Department',
  LoginHistory: 'LoginHistory',
  AccessReview: 'AccessReview',
  ApprovalWorkflow: 'ApprovalWorkflow',
  ApprovalStep: 'ApprovalStep',
  ApprovalDecision: 'ApprovalDecision',
  SupportCategory: 'SupportCategory',
  SupportTag: 'SupportTag',
  SupportArticle: 'SupportArticle',
  SupportArticleVersion: 'SupportArticleVersion',
  SupportDocument: 'SupportDocument',
  DownloadLog: 'DownloadLog',
  PropertyDocument: 'PropertyDocument',
  NotificationPreference: 'NotificationPreference',
  ConsentRecord: 'ConsentRecord',
  Session: 'Session',
  OwnerStatement: 'OwnerStatement',
  OwnerStatementLine: 'OwnerStatementLine',
  Disbursement: 'Disbursement',
  LandlordFavoriteDocument: 'LandlordFavoriteDocument',
  Conversation: 'Conversation',
  ConversationParticipant: 'ConversationParticipant',
  Message: 'Message',
  MessageAttachment: 'MessageAttachment',
  SupportCase: 'SupportCase',
  Task: 'Task',
  Project: 'Project',
  Subtask: 'Subtask',
  TaskComment: 'TaskComment',
  TaskAttachment: 'TaskAttachment',
  ImpersonationSession: 'ImpersonationSession',
  PlatformSecurityIncident: 'PlatformSecurityIncident',
  PlatformSecurityAlert: 'PlatformSecurityAlert',
  PlatformIntegration: 'PlatformIntegration',
  PlatformJob: 'PlatformJob',
  PlatformWebhook: 'PlatformWebhook',
  PlatformWebhookDelivery: 'PlatformWebhookDelivery',
  PlatformScheduledTask: 'PlatformScheduledTask',
  FeatureFlag: 'FeatureFlag',
  FeatureFlagOverride: 'FeatureFlagOverride',
  FeatureFlagVersion: 'FeatureFlagVersion',
  PlatformConfiguration: 'PlatformConfiguration',
  PlatformIncident: 'PlatformIncident',
  PlatformIncidentUpdate: 'PlatformIncidentUpdate',
  PlatformAffectedSystem: 'PlatformAffectedSystem',
  PlatformStatusEntry: 'PlatformStatusEntry',
  PlatformAlertRule: 'PlatformAlertRule',
  ReportTemplate: 'ReportTemplate',
  SavedReport: 'SavedReport',
  ScheduledReport: 'ScheduledReport',
  ReportExecution: 'ReportExecution',
  ReportExport: 'ReportExport',
  CollectionSetting: 'CollectionSetting'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
